import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ToasterContext from "./context/ToasterContext";
import AuthContext from "./context/AuthContext";


import { MainSidebar } from "@/app/(navigation)/Sidebar"
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthContext>
        <SidebarProvider>
          <MainSidebar />
          <SidebarInset >
            <header className="flex h-16 items-center border-b px-4">
              <SidebarTrigger />
              <h1 className="ml-4 text-lg font-semibold">Your task manager</h1>
            </header>
        <ToasterContext/>
        <main className="p-5">
        {children}
        </main>
        </SidebarInset>
        </SidebarProvider>
        </AuthContext>
      </body>
    </html>
  );
}
